name: Insert new tweets in database

concurrency: DatabaseUpdate

on: 
  schedule:
    - cron: '*/59 * * * *'
jobs:
  update_tweet_db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.1.12-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction
      - run: poetry run python src/random_tech_tweet_generator_backend/update_database.py new
        env:
          TWITTER_API_BEARER_TOKEN: ${{ secrets.TWITTER_API_BEARER_TOKEN }}
      - run: poetry run python src/random_tech_tweet_generator_backend/db_to_json.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update tweet database
          commit_author: debakarr <debakar.roy@outlook.com>
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Database updated successfully!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No new tweets to update in the database!"
